pipeline {
    agent any
    stages {
        stage('Contruccion de Aplicacion') {
            steps {
                sh 'mvn -f tomcat/pom.xml clean package'
            }
            post {
                success {
                    echo "El Archivo esta Guardado..."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Despliegue a Desarollo'){
            steps{
                build job: 'Despliegue_a_Desarollo_FRstyle'

            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'APRUEBA DESPLIEGUE A PRODUCTION ?'
                }
                build job: 'Deploy_Application_Prod_Env'
            }
        }
    }
}
